name: Deploy PHP app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Upload to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: siacmapa  # <-- Nombre exacto de tu Web App en Azure
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
